### ISSUE TITLE
-s/--select optuion doesn't work with sxhkd

### ISSUE THREAD

**Issue by user18130814200115-2** [pazuzu156/i3scrot#1]
Not sure if this is an issue with your script, scrot or sxhkd. The issue seems to be that if sxhkd in not ran from a terminal, it closes i3-scrot before the selection is complete.

This if fixed by adding "&" after the command eg:
```
Print + {_,shift,alt}
        i3-scrot {-d,-s,-w} &
```

**Comment by pazuzu156** [comment]
Hmm, I'll look into it. Thanks. Haven't made an update to this thing in some time

**Comment by user18130814200115-2** [comment]
This can also be solved by calling the program form 'i3-msg exec i3-scrot'
I made a fork that integrates this mechanic, though I am not sure if I should make a pull request

**Comment by pazuzu156** [comment]
Go ahead and make a PR and I'll give it a go

**Comment by pazuzu156** [comment]
Pull request merged and closed. Closing this issue too. Thanks for the submission! I'll work on updating it for the AUR as well
